---
language: python

python:
  - "3.7"

services:
  - docker

env:
  jobs:
    - distribution="robertdebock/docker-alpine-openrc:latest"
    - distribution="robertdebock/docker-alpine-openrc:edge"
    - distribution="archlinux/base"
    - distribution="robertdebock/docker-centos-systemd:7"
    - distribution="robertdebock/docker-centos-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:latest"
    - distribution="robertdebock/docker-debian-systemd:stable"
    - distribution="robertdebock/docker-debian-systemd:unstable"
    - distribution="robertdebock/docker-fedora-systemd:latest"
    - distribution="robertdebock/docker-fedora-systemd:rawhide"
    - distribution="opensuse/leap"
    - distribution="robertdebock/docker-ubuntu-systemd:latest"
    - distribution="robertdebock/docker-ubuntu-systemd:devel"
    - distribution="robertdebock/docker-ubuntu-systemd:rolling"

jobs:
  allow_failures:
    - env: distribution="alpine:edge"
    - env: distribution="robertdebock/docker-debian-systemd:unstable"
    - env: distribution="robertdebock/docker-fedora-systemd:rawhide"
    - env: distribution="robertdebock/docker-ubuntu-systemd:devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - echo $distribution
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "hCrXvNzLkRA8i+c95YE1gbOQ1DGKO9M6XlC0j725jcgBaaUJmcVwDMEzkcB38LKnpmNI8sBPaWFq0PXam+0h9nO+/dWG5+UhjO+dSWWMPpnjzK55sHTsaIAUecMSgPSB5f/X/h7+C8tzUR7GAFN7oXQyFh7UiAVU5xFkE+Vf/X8+l+0gNmr9eKI5uGyWYN/9attimM8tWx+6I89qGp/oTS7RO4gK9pS2ZVeZ7FPyHSqyQg9sIV7Pg+q/pJr4PM7Y+9ogXtYgqCxBGgQ3puzDiSDa1GtLOMkxhdH8RbU210feR9MbmNvFQ8pFA1vt2sp/ktrRUVb5vwqTEEcETqqCxVDlzK8Es/7RJQGc9OFQ46XU4GP3USd57HeEas7vdP3eBlOUauR+fyHiGoARhDGzb8PgWmnPm+JQDuqo/VVJYQPpuU8d+t/ZqlB/MecQeSGSnB/ZjfVgbvXqnXgI9IAfZsNKZHH0fCznPYyOD7Fih9oSTYWkWJ0Cn5gayiRiBk4QR4G2TaBYqZHa64gQBlZ6Lwm3JHb8H691l6e6hLMQ0rrsPxyb6/1ZEg8o+bdvVkK62F8Jn7wr8BLxqJreOM4MFmr00cfW7u3s6LmK1kA20irL28A6GWprJPjOikLps1kkoFpjQhnx4qXaa8hLxzct9ByjMi2Chhct5BBYMZ+jBog="
  email: false
