---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: redis-debian
    box: debian/stretch64
  - name: redis-fedora
    box: fedora/29-cloud-base
  - name: redis-opensuse
    box: opensuse/openSUSE-42.3-x86_64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
scenario:
  name: vagrant
